dist: bionic
language: bash
git:
  depth: false
install:
  - sudo add-apt-repository ppa:avsm/ppa -y
  - sudo apt update
  - sudo apt-get install opam
  - opam init --bare
  - opam update
  - opam switch create 4.10.0
  - opam repo add coq-released https://coq.inria.fr/opam/released
  - opam install coq-elpi
script:
  - coqc coq_fpc.v