dist: eoan
language: bash
git:
  depth: false
install:
  - sudo apt-get install opam
  - opam init
  - opam update
  - opam switch create 4.10.0
  - opam repo add coq-released https://coq.inria.fr/opam/released
  - opam install coq-elpi
script:
  - coqc coq_fpc.v