dist: bionic
language: bash
git:
  depth: false
install:
  - sudo add-apt-repository ppa:avsm/ppa -y
  - sudo apt update
  - sudo apt-get install opam
  - opam init --bare -a
  - eval $(opam config env)
  - opam update
  - opam switch create 4.10.0
  - opam repo add coq-released https://coq.inria.fr/opam/released
  - opam install -y -v coq-elpi
  - eval $(opam env) 
script:
  - coqc coq_fpc_dep.v