dist: bionic
language: bash
cache:
  directories:
    - $HOME/.opam
install:
  - sudo add-apt-repository ppa:avsm/ppa -y
  - sudo apt update
  - sudo apt-get install opam
  - opam init --bare -a
  - eval $(opam config env)
  - opam update
  - opam switch 4.10.0 || (opam switch create 4.10.0 &&
                           opam repo add coq-released https://coq.inria.fr/opam/released)
  - opam install -y -v coq-elpi
  - eval $(opam env) 
script:
  - coq_makefile -f _CoqProject -o Makefile
  - make